template: |
  <![CDATA[
  <div style="font-family: Arial, sans-serif; max-width: 800px; margin: 0 auto;">
    <div style="margin: 20px 0;">
      <div style="font-size: 20px; font-weight: bold; margin-bottom: 15px;">{title}</div>
      <div style="margin: 15px 0;">
        <div style="font-size: 16px; font-weight: bold;">Product Details:</div>
        <div style="margin: 10px 0;">
          <div>• Condition: {condition}</div>
          <div>• Professional UK Seller</div>
          <div>• Fast Shipping</div>
        </div>
      </div>
      <div style="margin: 15px 0;">
        <div style="font-size: 16px; font-weight: bold;">Shipping Information:</div>
        <div style="margin: 10px 0;">
          <div>• Royal Mail 2nd Class Delivery</div>
          <div>• 30 Day Return Policy</div>
          <div>• Secure Packaging</div>
        </div>
      </div>
    </div>
  </div>
  ]]> 